Refactor code to be more vue and nova compliant
badinansoft/nova-language-switch pull request #20
Opened 2024-05-17 21:22 UTC by scramatte

Hi,

With this PR , I've refactored source code to be more vue and nova compliant.
I've fixed too some cosmetic problem with Nova 4.33 

Hope that helps

Regards

2024-05-17 21:23 UTC, scramatte commented
Moreover , now, you can use any nova components  without change anything into tool.js file

2024-07-23 20:26 UTC, shahabzebare requested changes
Dear @scramatte ,

Thank you for your contribution to this useful package. Could you please fix those comments? Also, I apologize for the late response; I've been very busy.

Best regards,

2024-07-23 20:26 UTC, shahabzebare commented on resources/js/components/LanguageSwitcher.vue
> +      <span class="hidden md:inline">{{ selectedDisplay }}</span>
Remove this because some language names are too long, so we removed it in the last version.

2024-07-23 20:26 UTC, shahabzebare commented on resources/js/components/LanguageSwitcher.vue
> +    <Button variant="action" icon="globe-alt" class="text-primary-500 md:w-24" >
Also we don't need `md:w-24` for this version because we will keep only logo

2024-07-23 20:26 UTC, shahabzebare commented on resources/js/components/LanguageSwitcher.vue
> +      <span class="hidden md:inline">{{ selectedDisplay }}</span>
I this comment i mean this line 
`      <span class="hidden md:inline">{{ selectedDisplay }}</span>
`

2024-08-01 23:46 UTC, shahabzebare commented
Do in new commit https://github.com/badinansoft/nova-language-switch/pull/21

2024-08-01 23:46 UTC, closed without merging